### ISSUE TITLE
Needs TravisCI integration and Tests!

### ISSUE THREAD

**Issue by cscutcher** [leth/jenkins-pipeline-scheduledgate-plugin#2]
YOU MONSTER!!!!!

**Comment by leth** [comment]
:D Agreed!

This plugin is actually quite simple, most of the problems in developing this was of the "How does Jenkins even work", or "What happens if you restart Jenkins" variety; they're quite difficult to test unless you know Jenkins very well.

While I can grok Java (mostly) I have no idea how any of this maven stuff hangs together, beyond editing the `pom.xml` and running some voodoo.
Also I know nothing about java test frameworks or fitting tests into the jenkins behemoth.
Any advice/pull-requests greatly appreciated ;)
